<?php

namespace App\UniOne;

use App\UniOne\UniOne;

class Health
{
    /**
     * Checks that can connect to UniOne
     */
    public function checkApi() {
        $module = new UniOne;
        $result = $module->systemInfo();
        if ($result['status'] !== 'success') {
            return "status:{$result['status']}; code:{$result['code']}; message:{$result['message']}";
        }
        return true;
    }

    /**
     * Checks that webhook is set
     */
    public function checkWebhook() {
        $module = new UniOne;
        // $url can't be generated by the route() function, as it sets IP address
        // instead of domain.
        // The application will respond using the same domain as the request
        // (if there is one). It uses APP_URL in places where there is no request,
        // eg command line, tinker, queued jobs.
        // При запросе через браузер UniOne возвращает ошибку:
        //   Webhook with URL 'http://10.75.0.5/api/unione' not found
        // При запросе из командной строки работает нормально.
        // Для корректной работы надо правильно настроить вебсервер,
        // на что мы не можем рассчитывать.
        $url = rtrim(env('APP_URL'), '/') . '/' . ltrim(route('unione', [], false), '/');
        $requestBody = ['url' => $url];
        $result = $module->request('webhook/get.json', $requestBody);
        if ($result['status'] !== 'success') {
            return "status:{$result['status']}; code:{$result['code']}; message:{$result['message']}";
        }
        return true;
    }
}