@startuml Оплатить начисление
!pragma layout smetana

actor Клиент

Клиент -> Сервис : Открыть ссылку из письма
Сервис --> Клиент : Отобразить страницу подтверждения
Клиент -> Эквайринг : Перейти по ссылке оплаты
Эквайринг -> Эквайринг : Оплата
Эквайринг --> Клиент : Страница оплаты
Клиент -> Сервис : Результат оплаты
Сервис --> Клиент : 

@enduml